### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by Saeger** [pilipa-cn/jest-jenkins-reporter#10]
Perhaps I can work a little bit with the repository and improve the code a little bit.
Can you guys add me as a colaborator on this?

@zxkane @oyhanyu

**Comment by zxkane** [comment]
Saeger, thanks a lot for your interests. YES, definitely welcome to join this project. Or you prefer to forking this repo then take the future ownership?

**Comment by Saeger** [comment]
npmjs isn't getting latest version from this repo, which means that someone need to do it manually or include an automatic CI, which also means that, maybe ownership is a better approach, so I can automate those process?

I already forked the repo: https://github.com/Saeger/jest-jenkins-reporter
Should I proceed from there or?

**Comment by zxkane** [comment]
Saeger, thanks for taking the ownership of continuous development.

I already updated the README of repo to declare the future development support. Will archive this repo.
