### ISSUE TITLE
Dependencies use vulnerable version of braces

### ISSUE THREAD

**Issue by martinvaljaots** [pilipa-cn/jest-jenkins-reporter#4]
![image](https://user-images.githubusercontent.com/25842669/62689049-b441e980-b9d2-11e9-8fa5-6f4f3b1884d0.png)

Could the dependencies be updated so that a newer, more secure version of braces is used?

**Comment by Saeger** [comment]
I've made a pull request that fixes this.
It needs the repo admin to accept it now.
